language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
branches:
  only:
  - master
  - "/^releases\\/.*$/"
script: mvn test -DfailOnCheckstyleViolation=true
after_script:
- |
  declare exitCode
  curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
  exitCode=$?
  if [ $exitCode -eq 0 ]; then
      mvn deploy --settings travis-settings.xml
  fi
env:
  global:
  - secure: KwnRdPJ1M0PNGFhzGml4rE3VhKq2PfkgYBuDzuHnaXiLHuiX7gVcykURN4k97gMZcAeISMZVxpN3/g+l5EVykvMspJNDXJXyvbD5cRMzJRUph1SAYpLKWALLxelH+vb3jhYszC0mVQEuiw1yOSfpiSWwdPjAgZzQmYrfeQ4U4/tg9IcWbXv/KCemd6/q65eiEdhP2qVCxqwQty0mjpF/RCd5UnI3j+A9ukrZcRuUkovWMbRyDGHwSKw/oAI+xBt5+jT61iOIyZGMYeW3DE6TApXulycJWyqBhIDiiLG6QBHoa/b5lv1IMPSYG1GjmNvZ+++EMu+X38ovuHDB/4jqh+3g2qLS8k5d5IaIGUMn4+2DVrfG3DunmLFNuZ/rJR+GDxEP1Lyw/3u44tJ7O0X9jZyYXbI1AoD00Oga2gsiwt+/osv+slfr4244mNPaIa+2PJ5w1Ce5lNbRPWC0ryMhnII81zQ8jUnBOCUcg7urYIxhHPjrEKW1sx39VWUp6ho36n5cl67rWdyOvB/hQo1Rhi5mUad/sXB4Ty/kU1tPYJ13RVgxJyk/Myc5NrpNRms6jWhLG41YCQv61uMOBsw4BXr1S9bEp0IspFHuKfyXJm88Sa0bU3kmqA7FrxAaJs2tGe4BOW4lfocVlsm7h4PpLwXI9YdietFL36IiWcMRApI=
  - secure: iUcWarqaZIaqmSGp+f75iX5G5kIAokRDaJ3asq0yKydKEmyYy+eF+mymHS7DBVURhDUoSyUskNZ9AOL6xR1okrJFQsfVh4xr4gLSyxqmi0fzydAhW7qtKTBMJ1loZti3y8zEkJwv3oOIhxMhZ2lje8sGMbAKBJCn/xHP4ubkcqdmdrtdykuZ30M0TycbhK75dcBKBKvcPzoCtLmQ2Arv+cRvOM3prDanxQsbTcfcn9gNwWLN6QK/T9rHHS/WK9WN2gkmEgfN2fEcUnyov3Oqs5D9jacyICVtT9eOA3knSMQMcQWMolIv7Px9ReFnAeshB2XvaTRuyKh8wNTiqfRx1Rn4TqfS8zfDRzFtJvlIfFh+8Nv3dBMHXDqQ4KkrRt5Xc86I6tLFVKkPJI6p/IcNN6YbQp/LnkY3jgCGtpFLNgIQsl7gI0lVmJTtfy3zUSlBccYqyV/0D55MV988P9XVs0f+q/3ONcZY4ziI9QylrBJl9INGiQUeqchJ/sMe8ut12GzS04zqjSvqTQ+5bUUhJChtT/SOgl+8nfqL4QCkgU947hKsUCenafSqC5jCWNk3eM6oMSjMXmJ4WUsvoVUavPMTreZgTIIPbNxte1CNFDZgDhM09CxpVRnQ0xHowA45ST4z6AzuhYdT5TsSOS6ULDPl+OfGcM5/AywmB3B99tU=