language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
branches:
  only:
  - master
  - "/^releases\\/.*$/"
script: mvn test -DfailOnCheckstyleViolation=true
after_script:
- |
  declare exitCode
  curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
  exitCode=$?
  if [ $exitCode -eq 0 ]; then
      mvn deploy --settings travis-settings.xml
  fi
env:
  global:
  - secure: WGSevJWESVB3/LeYtlA2nEuG1woByAtDDEocVv5t9kNrWwUD80ZJS/cqIFCIH48Q5toJ6VoR1ynkEwQukvOkS2sQZfOMfKWKNsKnLWGiNkTiuVpvVCFc7zwznJbzVLeOihc1GbmVn/RA9+SFZVqy65Ctp+qhle4Y5+IBvqhlhU6E4A+bzRMaG6wOM9nVzLwYtcW/+PYTQISKGQSVfUVcZQHikifm0jiaWHUa3+RZfFDiv5jD+qHti9ef7Msb+XDezxSMMNDxbq4WZOWGiCBM+rH+Xpb3fa/ULoMt0yVI8lfH6o67MArHQW4tthQF7wh5hmOhnUlMygGQLae/LdcN5622BKXt+eSV2lfKaTr5u38IWFd6jSr2ysU2U3FyME5NygNR+/XliRTid+4+2Tgo8zIWK4PUSs2mw/5hlOVdr/ONYuuavznnhB6TYGiHqObHzHc06dFowgYvGE7PKYR5vFOvpgC2H3HW5zSEFHoTENIWsCzk9v9eckKjhjhVXTzhqHfU8CRRjAIW+bt0HBM52gwSyEJRIdx5WH1IkMbPV7WzbcSClVzCcwmHmu8Ybw52Qkbdx3Aj458toLwIB9H7zBBnjR4Jidm8pTgg4fUJBAndvd2xzRPXZy3pXGQBcd98e1yaRIwRWIaaqYxmxNfGzGA64FFO6ZRG4+VDlx7QXJA=
  - secure: KwnRdPJ1M0PNGFhzGml4rE3VhKq2PfkgYBuDzuHnaXiLHuiX7gVcykURN4k97gMZcAeISMZVxpN3/g+l5EVykvMspJNDXJXyvbD5cRMzJRUph1SAYpLKWALLxelH+vb3jhYszC0mVQEuiw1yOSfpiSWwdPjAgZzQmYrfeQ4U4/tg9IcWbXv/KCemd6/q65eiEdhP2qVCxqwQty0mjpF/RCd5UnI3j+A9ukrZcRuUkovWMbRyDGHwSKw/oAI+xBt5+jT61iOIyZGMYeW3DE6TApXulycJWyqBhIDiiLG6QBHoa/b5lv1IMPSYG1GjmNvZ+++EMu+X38ovuHDB/4jqh+3g2qLS8k5d5IaIGUMn4+2DVrfG3DunmLFNuZ/rJR+GDxEP1Lyw/3u44tJ7O0X9jZyYXbI1AoD00Oga2gsiwt+/osv+slfr4244mNPaIa+2PJ5w1Ce5lNbRPWC0ryMhnII81zQ8jUnBOCUcg7urYIxhHPjrEKW1sx39VWUp6ho36n5cl67rWdyOvB/hQo1Rhi5mUad/sXB4Ty/kU1tPYJ13RVgxJyk/Myc5NrpNRms6jWhLG41YCQv61uMOBsw4BXr1S9bEp0IspFHuKfyXJm88Sa0bU3kmqA7FrxAaJs2tGe4BOW4lfocVlsm7h4PpLwXI9YdietFL36IiWcMRApI=