language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
branches:
  only:
  - master
  - "/^releases\\/.*$/"
script: mvn test -DfailOnCheckstyleViolation=true
after_script:
- |
  declare exitCode
  curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
  exitCode=$?
  if [ $exitCode -eq 0 ]; then
      mvn deploy --settings travis-settings.xml
  fi
env:
  global:
  - secure: c1+6nqlKP04f2gT4Ncww0ZVCc+44+gQ5PCoGVRGReCMUsLCgVSIj8D2H6s97S6liUc7C6vm268ey5zmyboPSZWcTzftYL7YgkdBvtuDGIu5xo353pN2xoNwNnQ6Tem/qZvEJpQv0mKgv39c+bokctU5mQ+fVHe8UySQlkBzUH+RhklFnbqadMvLsrC+XOsQfvsRyGtTa1Rp4FQwLjTytdJZkVuOgcDJz6uopmCSfdmX5a+dB0OiUwtsCZ7xZsgBv5f10G+Nzw/yD/Kdx8BkcsM29nrIjTpHRf79+LUGLEZdwbfxW3wMjPRMDd8f27revBDIkaYF26cU5q5eB/c3oI4antHMSvGbg5tSEth9WDrsjimYSkoORSK3HovPr3g4z6sGJT3T52VGM0fayHLyuFzqQ3bnOELobrPasSC44S3tRYPu6P922GRiIwjNEbZUyZ7LCd6cldR5O1hH0TKcj1bnIQo4ppzdQA2XqEmPzVJliuTdeXijnZIrDlVxY5LJhcOvjzSpEmR0APQranDmgWzEqd1UG3tL5FkvgjKlNjgT5pULGu3Li13jopolkzR0z5VYSOnqt8m1Xnbh0WIcYm823yokcVv265KcLbwUx4JLGeeuQJs7gHz9CZIdFcIM4c02b7O0/K+U6kgZ5sMM//BJsGqbxqE5kXH9CFLY6JRM=
  - secure: CsxqH2OdOREaxUHUZRr2I+oHIvxvc2fsIvVNYX/C6FD5PlW37mWGvELBzlN5goH2EJvsnbkP9PtPx9CEIvzSXiMBS+uoG7Wn2RJWlgltdYre/2/nMg6vPZKy+hpTA7ObVeQlEAS5Busb0mkDHKyHznzWkw7TtJIoZLXr2Ui+EChVuuNDzpMKVBLZT4e++HE5G8oO7mWq5Hi1DsqAyhmTjb+8K617s2XfwDlnj+XOdrgHr1LEYaliGWVDXfEoP9IbwCdd8ZXsvjuGoUccJiHS3CvYSoQUXYnXxxGefX9cKb+P1ZkQIjn2dGh2bYtyB2haFULTc9VSSfbzydIJec37j9W5MN45RUTaE7VSYn3VGDlfrOFx/gwa1m1IgB56HqsZMKTDBxcrCaIGtwa1Y58jHsxbj9dqTrYVg+834qd7NwXUR572Rt8PMZOL1hnUZ6PTrqhyNp9Bp6duGTmY4yZ9sE1/FrIIK5FOSxsRUSoXnpH0DHp+rMLkkb+Ug598AjmM8h66FLpboSgRu795+e34ADUEZ/zTdSKXPQJbx/bM7M+yJahCR1PXC4DgDKSuXmuPbYxhWa1gjXJi1HlsEjNyFUtphcX5O84YwTKfNLM3EOkFKaLRSPijv5NgFqSfPz5OwNaWyuI2+JAaQSo/ZmGzTE9Bji3VOSwKvpuPBFOBebQ=